### ISSUE TITLE
Third party library used hasn't been updated in over a year

### ISSUE THREAD

**Issue by ndubbs** [Azure-Samples/active-directory-ios-native-nxoauth2-v2#6]
Could you provide an additional example on how to use Azure with an actively developed third party library?  

NXOAuth2Client was a good choice, however it has fallen into a state of abandonment.  Another option could be to clone the repo and perform the necessary updates that it requires.  I have started to do some of this work for my current project.  However, I have to postpone fixing the deprecations for NSURLConnection.

**Comment by brandwe** [comment]
@ndubbs You are correct that it appears the library is not being actively maintained. We also have a B2C sample that uses AppAuth that we hope to build a sample for in the near future.

**Comment by ndubbs** [comment]
Thanks for the response.  Please keep us posted when that example is released.

**Comment by jmprieur** [comment]
Closing as the repo is being archived
